# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a7e9e640f93ac32a2fd3c97761b606999498a0f5194fe598ae0e99cf9a34022a4db3f7784a250a362f970adb2633347f65136ad5de8f498e62d2a7cc5946ec

test:
  secret_key_base: 395d3ac5ad73eed26c66f4b18c336ba331bf17303d6fbdf99131ddabefe9c35901e6dbbed7909734d2a75f1daf9e6654b80d9b63345b3e45c862933bee353ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
